<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TrayApp.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ParserTests.fs" />
    <Compile Include="DatabaseTests.fs" />
    <Compile Include="PubSubTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TrayApp.Core/TrayApp.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../TrayApp/doctypes/**/*.json" CopyToOutputDirectory="PreserveNewest" Link="doctypes/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
